services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/portfolio/Dockerfile
      -ARGS:
        - PROYECTO=${PROYECTO}
    container_name: ctportfolio
    ports:
      - "${PORT_WEB}:80" 
    env_file:
      - ./.env