services:
  web:
    build: 
      context: .. #portfolio
      args: #variables en dockerfile para la construcci√≥n de la
        - USUARIO=maria
      dockerfile: ./deploy/Dockerfile
    container_name: ctportfolio
    ports:
      - "8810:80"

