apiVersion: apps/v1
kind: Deployment 
metadata:
  name: portfolio-deployment
  namespace: miportfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miportfolio
  template:
    metadata:
      labels:
        app: miportfolio
    spec:
      containers:
      - name: miportfolio
        image: peedroorgzz/portfolio
        imagePullPolicy: Always
        ports:
        - containerPort: 80
