apiVersion: v1
kind: Service
metadata:
  name: portfolio-taller
  namespace: miportfolio
spec:
  type: NodePort
  selector:
    app: miportfolio
  ports:  
  - port: 80
    targetPort: 80
    nodePort: 30081
