services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - axial
      - zoro
    networks:
      - app_network

  axial:
    build:
      context: ../axial-andromeda
      dockerfile: Dockerfile
    container_name: axial_app
    networks:
      - app_network

  zoro:
    build:
      context: ../one-piece-app
      dockerfile: deploy/Dockerfile
    container_name: zoro_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
