services:
  web:
    build: 
      context: /home/pedro/HLC/devops/Docker/Caronte
      #args: #variables en dockerfile para la construcci√≥n de la imagen
      #  - USUARIO=pedro
    dockerfile: ./dockerfiles/base/ubbase
    container_name: ctpbase
    ports:
      - "8810:80"
    environmment: #variables que se usan cuando se ejecuta el contenedor.
        - USUARIO=pedro
