services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/node/Dockerfile
      args:
        - PROYECTO=${PROYECTO}
    container_name: ${NOMBRE}
    ports:
      - "${PORT_WEB}:3000"   
    env_file:
      - ./.env
    image: peedroorgzz/nodejs
    volumes:
      - ./logs:/root/logs      
      - ../../pokeapi/:/root/admin/node/proyectos/pokeapi/
    networks:
      netpokeapi:
        ipv4_address: ${IP}

networks:
  netpokeapi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}