apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{.Values.app.name}}
  namespace: {{.Release.Namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{.Values.app.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-taller
                port:
                  number: {{.Values.app.service.port}}
