apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
  namespace: {{.Release.Namespace}}
spec:
  type: NodePort
  selector:
    app: {{.Values.app.name}}
  ports:  
  - port: {{.Values.app.service.port}}
    targetPort: {{.Values.app.service.port}}
    nodePort: {{.Values.app.service.nodePort}}